#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-pmaven
Version  : 0.7
Release  : 1
URL      : https://github.com/mkmik/polyglot-maven/archive/pmaven-0.7.tar.gz
Source0  : https://github.com/mkmik/polyglot-maven/archive/pmaven-0.7.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/org/sonatype/pmaven/pmaven-common/0.8-20100325/pmaven-common-0.8-20100325.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/org/sonatype/pmaven/pmaven-common/0.8-20100325/pmaven-common-0.8-20100325.pom
Source3  : https://repo.gradle.org/gradle/libs-releases/org/sonatype/pmaven/pmaven-groovy/0.8-20100325/pmaven-groovy-0.8-20100325.jar
Source4  : https://repo.gradle.org/gradle/libs-releases/org/sonatype/pmaven/pmaven-groovy/0.8-20100325/pmaven-groovy-0.8-20100325.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-pmaven-data = %{version}-%{release}

%description
Description
-----------
Sonatype [Polyglot Maven](http://polyglot.sonatype.org/).

%package data
Summary: data components for the mvn-pmaven package.
Group: Data

%description data
data components for the mvn-pmaven package.


%prep
%setup -q -n polyglot-maven-pmaven-0.7

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/pmaven/pmaven-common/0.8-20100325
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/pmaven/pmaven-common/0.8-20100325/pmaven-common-0.8-20100325.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/pmaven/pmaven-common/0.8-20100325
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/pmaven/pmaven-common/0.8-20100325/pmaven-common-0.8-20100325.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/pmaven/pmaven-groovy/0.8-20100325
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/pmaven/pmaven-groovy/0.8-20100325/pmaven-groovy-0.8-20100325.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/sonatype/pmaven/pmaven-groovy/0.8-20100325
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/sonatype/pmaven/pmaven-groovy/0.8-20100325/pmaven-groovy-0.8-20100325.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/sonatype/pmaven/pmaven-common/0.8-20100325/pmaven-common-0.8-20100325.jar
/usr/share/java/.m2/repository/org/sonatype/pmaven/pmaven-common/0.8-20100325/pmaven-common-0.8-20100325.pom
/usr/share/java/.m2/repository/org/sonatype/pmaven/pmaven-groovy/0.8-20100325/pmaven-groovy-0.8-20100325.jar
/usr/share/java/.m2/repository/org/sonatype/pmaven/pmaven-groovy/0.8-20100325/pmaven-groovy-0.8-20100325.pom
